name: En Son Blog Yazılarını Çek
on:
  schedule:
    # Her 12 saatte bir çalışır
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: README dosyasını en son blog yazılarıyla güncelle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-list@v1
        with:
          feed_list: "https://medium.com/feed/@sahinbolukbasii"
